###
POST http://localhost:3000/token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJ1c2VyTmFtZSI6Im1hcmsiLCJyb2xlcyI6W3sicHJpdmlsZWdlcyI6W10sIl9pZCI6IjVmMTgzMjVkNmI4ZmJhMTBhOGZmNmY1YyIsIm5hbWUiOiJzZWxsZXIifV0sImVtcGxveWluZ1N0b3JlcyI6W3siX2lkIjoiNWYxODMyNWQ2YjhmYmExMGE4ZmY2ZjVkIiwic3RvcmVJZCI6IjVmMTgzMjVkNmI4ZmJhMTBhOGZmNmY1YSIsInN0b3JlTmFtZSI6Im1hcmt1c1Nob2VzIn1dfSwiaWF0IjoxNTk1NzY5NzA0LCJleHAiOjE1OTU4NTYxMDR9.JA2MMYKfslI6NzcY4JaVhw38k_ZweGcRlprLr6pRUes

###
DELETE http://localhost:3000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJ1c2VyTmFtZSI6Im1hcmsiLCJyb2xlcyI6W3sicHJpdmlsZWdlcyI6W10sIl9pZCI6IjVlZmM4MjZhMjhmZGIzMDE1MDM2NjcxNiIsIm5hbWUiOiJidXllciJ9XX0sImlhdCI6MTU5NTE1Mjg5OSwiZXhwIjoxNTk1MjM5Mjk5fQ.7xrz8C1bD9EPowZTH5XCxv-HyJwb1FAHx_RmLKFjiYs

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "userName": "mark",
    "password": "Cacnga@153."
}

{"message":"successful login",
"accessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJ1c2VyTmFtZSI6Im1hcmsiLCJyb2xlcyI6W3sicHJpdmlsZWdlcyI6W10sIl9pZCI6IjVmMTgzMjVkNmI4ZmJhMTBhOGZmNmY1YyIsIm5hbWUiOiJzZWxsZXIifV0sImVtcGxveWluZ1N0b3JlcyI6W3siX2lkIjoiNWYxODMyNWQ2YjhmYmExMGE4ZmY2ZjVkIiwic3RvcmVJZCI6IjVmMTgzMjVkNmI4ZmJhMTBhOGZmNmY1YSIsInN0b3JlTmFtZSI6Im1hcmt1c1Nob2VzIn1dfSwiaWF0IjoxNTk1NzY5NzA0LCJleHAiOjE1OTU3NzMzMDR9.z54wSUsdoaHwaZ_h_wocJkOBFrMYbEArI-fZtCmoPew",
"refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJ1c2VyTmFtZSI6Im1hcmsiLCJyb2xlcyI6W3sicHJpdmlsZWdlcyI6W10sIl9pZCI6IjVmMTgzMjVkNmI4ZmJhMTBhOGZmNmY1YyIsIm5hbWUiOiJzZWxsZXIifV0sImVtcGxveWluZ1N0b3JlcyI6W3siX2lkIjoiNWYxODMyNWQ2YjhmYmExMGE4ZmY2ZjVkIiwic3RvcmVJZCI6IjVmMTgzMjVkNmI4ZmJhMTBhOGZmNmY1YSIsInN0b3JlTmFtZSI6Im1hcmt1c1Nob2VzIn1dfSwiaWF0IjoxNTk1NzY5NzA0LCJleHAiOjE1OTU4NTYxMDR9.JA2MMYKfslI6NzcY4JaVhw38k_ZweGcRlprLr6pRUes",
"role":"seller"}

### CREATE PRODUCT - only for authenicated users
POST http://localhost:3000/product/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJ1c2VyTmFtZSI6Im1hcmsiLCJyb2xlcyI6W3sicHJpdmlsZWdlcyI6W10sIl9pZCI6IjVmMTgzMjVkNmI4ZmJhMTBhOGZmNmY1YyIsIm5hbWUiOiJzZWxsZXIifV0sImVtcGxveWluZ1N0b3JlcyI6W3siX2lkIjoiNWYxODMyNWQ2YjhmYmExMGE4ZmY2ZjVkIiwic3RvcmVJZCI6IjVmMTgzMjVkNmI4ZmJhMTBhOGZmNmY1YSIsInN0b3JlTmFtZSI6Im1hcmt1c1Nob2VzIn1dfSwiaWF0IjoxNTk1NzY5NzA0LCJleHAiOjE1OTU3NzMzMDR9.z54wSUsdoaHwaZ_h_wocJkOBFrMYbEArI-fZtCmoPew
Content-Type: application/json

{
    "name": "Polo Shirt",
    "storeId": "5f18325d6b8fba10a8ff6f5a",
    "status": "online",
    "productType": "simple"
}


### UPDATE Product - Needs authorization
PATCH http://localhost:3000/product/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJ1c2VyTmFtZSI6Im1hcmsiLCJyb2xlcyI6W3sicHJpdmlsZWdlcyI6W10sIl9pZCI6IjVmMTgzMjVkNmI4ZmJhMTBhOGZmNmY1YyIsIm5hbWUiOiJzZWxsZXIifV0sImVtcGxveWluZ1N0b3JlcyI6W3siX2lkIjoiNWYxODMyNWQ2YjhmYmExMGE4ZmY2ZjVkIiwic3RvcmVJZCI6IjVmMTgzMjVkNmI4ZmJhMTBhOGZmNmY1YSIsInN0b3JlTmFtZSI6Im1hcmt1c1Nob2VzIn1dfSwiaWF0IjoxNTk1NzY5NzA0LCJleHAiOjE1OTU3NzMzMDR9.z54wSUsdoaHwaZ_h_wocJkOBFrMYbEArI-fZtCmoPew
Content-Type: application/json

{
    "id": "5f1d843cf87a663d001d708d",
    "name": "Nike Shirt",
    "productType": "variable"
}

### CREATE PRODUCT - for public users, no authentication
GET http://localhost:3000/product/search
Content-Type: application/json

{
    "name": ""
}

### DELETE Product - Needs authorization
DELETE http://localhost:3000/product/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRGF0YSI6eyJ1c2VyTmFtZSI6Im1hcmsiLCJyb2xlcyI6W3sicHJpdmlsZWdlcyI6W10sIl9pZCI6IjVmMTgzMjVkNmI4ZmJhMTBhOGZmNmY1YyIsIm5hbWUiOiJzZWxsZXIifV0sImVtcGxveWluZ1N0b3JlcyI6W3siX2lkIjoiNWYxODMyNWQ2YjhmYmExMGE4ZmY2ZjVkIiwic3RvcmVJZCI6IjVmMTgzMjVkNmI4ZmJhMTBhOGZmNmY1YSIsInN0b3JlTmFtZSI6Im1hcmt1c1Nob2VzIn1dfSwiaWF0IjoxNTk1NjI1Mjc4LCJleHAiOjE1OTU2Mjg4Nzh9._mPAT2tNK1eSeJu6T78FbaXTwi-Jubyhes3ZHHEqV0g
Content-Type: application/json

{
    "id": "5f1b4fad06a7dc0378b7dab9"
}


### REGISTER A USER
POST http://localhost:3000/register/buyer
Content-Type: application/json

{
    "userName": "cacious8",
    "firstName": "cacious",
    "lastName": "siamunyanga",
    "email": "cacious8@hotmail.com",
    "password": "Cacnga@153."
}

### REGISTER A SELLER
POST http://localhost:3000/register/seller
Content-Type: application/json

{
    "userName": "mark",
    "firstName": "markus",
    "lastName": "phiri",
    "userEmail": "mark@outlook.com",
    "storeName": "markusShoes",
    "password": "Cacnga@153."
}

###
GET http://localhost:3000/
